version: 1.2
workflows:
  - name: PrepareReference
    subclass: WDL
    primaryDescriptorPath: /PrepareReference.wdl
    publish: true
  - name: ComputeGL
    subclass: WDL
    primaryDescriptorPath: /ComputeGL.wdl
    publish: true
  - name: RepackGL
    subclass: WDL
    primaryDescriptorPath: /RepackGL.wdl
    publish: true
  - name: PhaseLigate
    subclass: WDL
    primaryDescriptorPath: /PhaseLigate.wdl
    publish: true
  - name: PhaseLigateOnly
    subclass: WDL
    primaryDescriptorPath: /PhaseLigateOnly.wdl
    publish: true
